# [作業目標]

1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。
2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



# 作業 

### 1. 產生一個 1-11 的一維陣列，並且把 3-6 由正數變成負數。



In [1]:
# 記得先 Import 正確的套件

import numpy as np

In [33]:
x = np.arange(1,12,1)

y=[]
for i in x:
    if i>2 and i<7:
        y.append(i*(-1))
    else:
        y.append(i*(1))
print(y)

x[(x>2)&(x<7)]*=(-1)
print(x)
    

[1, 2, -3, -4, -5, -6, 7, 8, 9, 10, 11]
[ 1  2 -3 -4 -5 -6  7  8  9 10 11]


### 2. 試著從一個隨機陣列中，找出比 0.5 大的數有幾個？



In [29]:
A = np.random.rand(3, 6)

print(A)

print(A[A>0.5])


[[0.8955206  0.75041929 0.29487636 0.8632051  0.73043851 0.05646244]
 [0.54145601 0.23825063 0.58994572 0.78058422 0.73641791 0.87864232]
 [0.46058847 0.36410504 0.40906037 0.30306996 0.32400219 0.24697787]]
[0.8955206  0.75041929 0.8632051  0.73043851 0.54145601 0.58994572
 0.78058422 0.73641791 0.87864232]
