# [作業目標]

1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```

2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。
3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

# 作業 

### 1. [簡答題] 請比較 np.zeros 和 np.empty 產生出來的陣列有何差異？為什麼要設計兩種方法？

```
print(np.zeros((2, 3)))
print(np.empty((2, 3)))
```


In [22]:
"np.zero陣列全部由0所組成，np.empty由區進餘0的數所組成。"
"np.empty只是初始化的值，會被之後其他值複寫進去，如果要更修正用這個比較方便"

'np.zero陣列全部由0所組成，np.empty由區進餘0的數所組成。'

### 2. 在不用「整數亂數方法」的限制下，如何將包含小數的轉換整數？請將給定的 a 陣列當中的元素變成去掉小數變成整數。


In [7]:
# 記得先 Import 正確的套件

import numpy as np
from numpy.random import default_rng


In [37]:
# 參考解答
##然後就用round四捨五入了(？？？

a = np.random.rand(2,3)
print(a.round)
print(np.round(a))

##不用四捨五入的方法
b= a % 1
c=a-b
print(c)



<built-in method round of numpy.ndarray object at 0x0000021F2748AF90>
[[0. 0. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]


### 3. 承上題，怎樣可以限制整數的範圍介於 m - n 之間？請將給定的 a 陣列當中的元素的範圍調整成 m - n 之間。

In [39]:
# %為除後數的餘數

m = 20
n = 40
a = np.random.rand(2,3)
a=b
print((b- a % 1)+m)




[[20. 20. 20.]
 [20. 20. 20.]]
